/**
 * @file fsrs-engine.ts
 * @description Adapter layer linking the application domain and the `ts-fsrs` scheduling engine.
 *
 * Implements SRS-FR-072 by handling conversion between versioned JSON-serializable states
 * and `ts-fsrs` library class models, enforcing compatibility boundaries.
 */

import { createEmptyCard, fsrs, Card } from 'ts-fsrs'
import { FsrsState } from '../../../shared/domain/item'
import { FsrsRatingValue } from '../../../shared/domain/log'
import { DateTimeString } from '../../../shared/domain/types'

/**
 * Parameters submitted to calculate the next repetition date.
 */
export interface ScheduleInput {
  /** The current versioned FSRS state of the item */
  state: FsrsState
  /** The FSRS rating value mapped to the range [1, 4] */
  rating: FsrsRatingValue
  /** The UTC ISO 8601 date when the review took place */
  reviewedAt: DateTimeString
}

/**
 * Result returned by the FSRS calculation.
 */
export interface ScheduleResult {
  /** The calculated next due date in UTC ISO 8601 format */
  dueAt: DateTimeString
  /** The calculated versioned FSRS state to persist */
  state: FsrsState
}

/**
 * Interface representing the FSRS calculation engine adapter.
 */
export interface FsrsEngine {
  /** Initializes a versioned default state for a brand new review item */
  createInitialState(reviewedAt: DateTimeString): FsrsState
  /** Performs scheduling calculations using ts-fsrs and returns serialized outputs */
  schedule(input: ScheduleInput): ScheduleResult
}

/**
 * Factory function to instantiate the FSRS engine adapter.
 *
 * It bridges pure JSON-serializable state constructs to the `ts-fsrs` package API,
 * ensuring that library objects (like standard Date objects) are parsed/serialized correctly.
 *
 * @returns FsrsEngine instance.
 */
export function createFsrsEngine(): FsrsEngine {
  /** The exact version tag representing the current adapter schema */
  const version = 'ts-fsrs@5'
  
  /** The core library scheduler engine */
  const f = fsrs()

  return {
    createInitialState(reviewedAt: DateTimeString): FsrsState {
      // Create a default initial card state starting at the specified reviewedAt date
      const card = createEmptyCard(new Date(reviewedAt))
      
      // Serialize date fields into ISO 8601 UTC strings to guarantee JSON compatibility
      return {
        version,
        payload: {
          due: card.due.toISOString(),
          stability: card.stability,
          difficulty: card.difficulty,
          elapsed_days: card.elapsed_days,
          scheduled_days: card.scheduled_days,
          reps: card.reps,
          lapses: card.lapses,
          state: card.state,
          last_review: card.last_review ? card.last_review.toISOString() : null,
          learning_steps: card.learning_steps
        }
      }
    },

    schedule({ state, rating, reviewedAt }: ScheduleInput): ScheduleResult {
      // Reject states generated by a different or incompatible version of the scheduler
      if (state.version !== version) {
        throw new Error(`Incompatible version: ${state.version}`)
      }

      // Clone target state to prevent modifying external references
      const stateCopy = structuredClone(state)

      // Reconstruct the library-compatible Card interface, translating ISO strings back to Date objects
      const card: Card = {
        due: new Date(stateCopy.payload.due as string),
        stability: stateCopy.payload.stability as number,
        difficulty: stateCopy.payload.difficulty as number,
        elapsed_days: stateCopy.payload.elapsed_days as number,
        scheduled_days: stateCopy.payload.scheduled_days as number,
        reps: stateCopy.payload.reps as number,
        lapses: stateCopy.payload.lapses as number,
        state: stateCopy.payload.state as number,
        last_review: stateCopy.payload.last_review ? new Date(stateCopy.payload.last_review as string) : undefined,
        learning_steps: (stateCopy.payload.learning_steps as number) ?? 0
      }

      // Execute next scheduling step through ts-fsrs engine
      const result = f.next(card, new Date(reviewedAt), rating)

      // Format outputs back to versioned JSON-serializable structures with string timestamps
      return {
        dueAt: result.card.due.toISOString() as DateTimeString,
        state: {
          version: stateCopy.version,
          payload: {
            due: result.card.due.toISOString(),
            stability: result.card.stability,
            difficulty: result.card.difficulty,
            elapsed_days: result.card.elapsed_days,
            scheduled_days: result.card.scheduled_days,
            reps: result.card.reps,
            lapses: result.card.lapses,
            state: result.card.state,
            last_review: result.card.last_review ? result.card.last_review.toISOString() : null,
            learning_steps: result.card.learning_steps
          }
        }
      }
    }
  }
}
